### PR TITLE
Acquisition software

### PR DESCRIPTION
**Pull request by proscrite**

### CODE REVIEW

**Review by jjgomezcadenas — COMMENTED** [review]
It is good to see such a bit commit!

But you need to organise it better!

1. You cannot commit dll files to git
2. You cannot commit pyc files
3.  You seem to try to commit ll_cmold_old.jl
4. and also ll_cmos_PHG_LPF.jl

I am not interested in an old version of my code. Do you have something new to bring to my new version? I this case the PR should propose changes to my code (that I will approve or not) and not polute the space with more version of the code. There cannot be a ll_cmos version from me, another from you and another from MIkel....

Also, this PR is way too big.

Fix it like this:
1. remove all binary code
2. commit a directory acquisition_sw, with only py and m files.

We then approve that part (acquisition sofware). Submit a separate PR to propose any change to ll_cmos. These are completely different topics and requires different PRs.

**Comment by proscrite** [comment]
Fixed this issues, I will open new pull request with an small adaptation for windows in ll_cmos.jl

**Review by jjgomezcadenas — COMMENTED** [review]
You don't need a new PR, just keep improving on this one

**Comment by jjgomezcadenas** [comment]
Remove ll_cmos from the commit

**Pull request closed without merging**
